services:
  tag_backend:
    build: .
    container_name: tag_impl_backend
    ports:
      - "8006:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - APP_ENV=docker
      # DB: Connect to host machine's MySQL
      - DATABASE_URL=${DATABASE_URL}
      # Redis: Connect to this container
      - REDIS_URL=redis://redis:6379/0
      # ES: Connect to this container
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tag_network
      - lightningbot_ai_network

  redis:
    image: redis:7.2
    container_name: tag_impl_redis
    ports:
      - "6384:6379" # Host 6384 -> Container 6379 to avoid conflict if local redis running
    networks:
      - tag_network

networks:
  tag_network:
    driver: bridge
  lightningbot_ai_network:
    external: true
