"""Enum mappings for domain columns."""

# Label to stored-value mappings (for INSERT/UPDATE)
ENUM_MAPPINGS = {
    "alert_type": {
        "none": 0,
        "open_alert": 1,
        "device_alert": 2,
        "other_alert": 3,
    },
    "category": {
        "none": 0,
        "dealer_owned": 1,
        "transporter_owned": 2,
        "customer_owned": 3,
        "transporter_exmi": 4,
    },
    "emergency_status": {
        "off": 0,
        "on": 1,
    },
    "ignition_status": {
        "off": 0,
        "on": 1,
    },
    "implementation_status": {
        "not_yet_started": 0,
        "partially_completed": 1,
        "completed": 2,
        "pilot": 3,
    },
    "invoice_category": {
        "delivered_supply": "DDP",
        "exmi_supply": "EXW",
        "expo_duty_fg_supply": "ZEN3",
    },
    "invoice_type": {
        "normal": 0,
        "pre": 1,
        "post": 2,
    },
    "packet_status": {
        "history": "H",
        "live": "L",
    },
    "packet_type": {
        "ignition_off": "IF",
        "ignition_on": "IN",
        "harsh_acceleration": "HA",
        "harsh_manoeuvring": "HT",
        "internal_battery_reconnect": "BC",
        "voice_alert": "VA",
        "parameter_change": "PC",
        "tilt_detection": "TD",
        "dislocation": "DL",
        "emergency_alert": "EA",
        "tamper_alert": "TA",
        "health_packet": "HP",
        "vehicle_battery_disconnect": "BD",
        "vehicle_battery_reconnect": "BR",
        "internal_battery_low": "BL",
        "normal": "NR",
        "harsh_braking": "HB",
    },
    "recent_state_id": {
        "created": 10,
        "invoice_received": 60,
        "crew_identification_ro": 11,
        "complete_otp_sent_unloading": 12,
        "unloading_lock_one": 13,
        "unloading_lock_two": 14,
        "complete_otp_sent_unloaded": 15,
        "unloaded_lock_one": 16,
        "unloaded_lock_two": 17,
        "not_used": 18,
        "vehicle_entered": 20,
        "cancel": 70,
        "en_route": 9,
        "crew_identification_terminal": 4,
        "reached": 40,
        "loading_lock_one": 5,
        "destination_exit": 90,
        "loading_lock_two": 6,
        "loaded_lock_one": 7,
        "loaded_lock_two": 8,
    },
    "report_type": {
        "none": 0,
        "mis_report": 1,
        "terminal_communication": 10,
        "login_credential": 11,
        "device_configuration_otp": 12,
        "device_removed_communication": 13,
        "over_speed": 14,
        "route_deviation": 15,
        "halt_time_deviation": 16,
        "night_halt": 18,
        "continues_driving": 19,
        "vehicle_check_report": 2,
        "night_driving": 20,
        "gps_not_available": 21,
        "harsh_braking": 22,
        "harsh_acceleration": 23,
        "harsh_manoeuvring": 24,
        "driving": 25,
        "emergency_alert": 26,
        "tamper_alert": 27,
        "sms_limit_excess_mobile_numbers_report": 3,
        "unauthorised_alert": 4,
        "rule_generation_error_alert": 5,
        "trip_completion_report": 6,
        "communication_issue": 7,
        "rule_generate_error_for_inactive_entity": 8,
        "notify_vehicle_trip_creation": 9,
    },
    "type": {
        "none": 0,
        "terminal": 1,
        "reached": 10,
        "invoice_received": 100,
        "crew_identification_ro": 11,
        "complete_otp_sent_unloading": 12,
        "unloading_lock_one": 13,
        "unloading_lock_two": 14,
        "complete_otp_sent_unloaded": 15,
        "unloaded_lock_one": 16,
        "unloaded_lock_two": 17,
        "not_used": 18,
        "dynamic": 2,
        "partially_used": 20,
        "cancel": 21,
        "crew_identification_terminal": 4,
        "loading_lock_one": 5,
        "loading_lock_two": 6,
        "loaded_lock_one": 7,
        "loaded_lock_two": 8,
        "en_route": 9,
        "destination_exit": 90,
    },
}

# Stored-value to label mappings (for SELECT display)
ENUM_LABELS = {
    "alert_type": {
        0: "None",
        1: "Open Alert",
        2: "Device Alert",
        3: "Other Alert",
    },
    "category": {
        0: "NONE",
        1: "Dealer owned",
        2: "Transporter owned",
        3: "Customer owned",
        4: "Transporter exmi",
    },
    "emergency_status": {
        0: "Off",
        1: "On",
    },
    "ignition_status": {
        0: "Off",
        1: "On",
    },
    "implementation_status": {
        0: "Not yet started",
        1: "Partially completed",
        2: "Completed",
        3: "Pilot",
    },
    "invoice_category": {
        0: "Delivered supply",
        1: "Delivered supply",
        2: "EXMI supply",
        3: "EXPO DUTY FG supply",
        "DAS": "Delivered supply",
        "DDP": "Delivered supply",
        "EXW": "EXMI supply",
        "ZEN3": "EXPO DUTY FG supply",
    },
    "invoice_type": {
        0: "NORMAL",
        1: "PRE",
        2: "POST",
    },
    "packet_status": {
        "H": "History",
        "L": "Live",
    },
    "packet_type": {
        0: "Ignition Off",
        1: "Ignition On",
        10: "Harsh Acceleration",
        11: "Harsh Manoeuvring",
        12: "Internal Battery Reconnect",
        13: "Voice Alert",
        14: "Parameter Change",
        15: "Tilt Detection",
        16: "Dislocation",
        2: "Emergency Alert",
        3: "Tamper Alert",
        4: "Health Packet",
        5: "Vehicle Battery Disconnect",
        6: "Vehicle Battery Reconnect",
        7: "Internal Battery Low",
        8: "Normal",
        9: "Harsh Braking",
        "BC": "Internal Battery Reconnect",
        "BD": "Vehicle Battery Disconnect",
        "BL": "Internal Battery Low",
        "BR": "Vehicle Battery Reconnect",
        "DL": "Dislocation",
        "EA": "Emergency Alert",
        "HA": "Harsh Acceleration",
        "HB": "Harsh Braking",
        "HP": "Health Packet",
        "HT": "Harsh Manoeuvring",
        "IF": "Ignition Off",
        "IN": "Ignition On",
        "NR": "Normal",
        "PC": "Parameter Change",
        "TA": "Tamper Alert",
        "TD": "Tilt Detection",
        "VA": "Voice Alert",
    },
    "recent_state_id": {
        1: "Created",
        10: "Created",
        100: "Invoice Received",
        11: "Crew Identification Ro",
        12: "Complete (OTP sent Unloading)",
        13: "Unloading lock One",
        14: "Unloading lock Two",
        15: "Complete (OTP sent Unloaded)",
        16: "Unloaded lock One",
        17: "Unloaded lock Two",
        18: "Not used",
        2: "Vehicle Entered",
        20: "Vehicle Entered",
        21: "Cancel",
        30: "En route",
        4: "Crew Identification Terminal",
        40: "Reached",
        5: "Loading lock one",
        50: "Destination Exit",
        6: "Loading lock two",
        60: "Invoice Received",
        7: "Loaded lock one",
        70: "Cancel",
        8: "Loaded lock two",
        9: "En route",
        90: "Destination Exit",
    },
    "report_type": {
        0: "None",
        1: "MIS report",
        10: "Terminal Communication",
        11: "Login Credential",
        12: "Device Configuration OTP",
        13: "Device removed communication",
        14: "Over Speed",
        15: "Route deviation",
        16: "Halt time deviation",
        18: "night halt",
        19: "continues driving",
        2: "Vehicle check report",
        20: "night driving",
        21: "gps not available",
        22: "Harsh braking",
        23: "Harsh acceleration",
        24: "Harsh manoeuvring",
        25: "Driving",
        26: "Emergency Alert",
        27: "Tamper Alert",
        3: "SMS limit excess mobile numbers report",
        4: "Unauthorised alert",
        5: "Rule generation error alert",
        6: "Trip completion report",
        7: "Communication issue",
        8: "Rule generate error for inactive entity",
        9: "Notify vehicle trip creation",
    },
    "type": {
        0: "NONE",
        1: "Terminal",
        10: "Reached",
        100: "Invoice Received",
        11: "Crew Identification Ro",
        12: "Complete (OTP sent Unloading)",
        13: "Unloading lock One",
        14: "Unloading lock Two",
        15: "Complete (OTP sent Unloaded)",
        16: "Unloaded lock One",
        17: "Unloaded lock Two",
        18: "Not used",
        2: "Dynamic",
        20: "Partially used",
        21: "Cancel",
        4: "Crew Identification Terminal",
        5: "Loading lock one",
        6: "Loading lock two",
        7: "Loaded lock one",
        8: "Loaded lock two",
        9: "En route",
        90: "Destination Exit",
    },
}

